language: python
python:
  - "2.7"
# command to install dependencies
install:
  - easy_install distribute
  - pip install -r requirements.txt
# command to run tests

script:
  - python -m pytest --cov=app tests
after_success:
  - coveralls